### ISSUE TITLE
ch_08_prefix_span.R

### ISSUE THREAD

**Issue by pendl** [batermj/learning-data-mining-with-r#2]
Hello,
is it possible to get access to the script ch_08_prefix_span.R?
Kind Regards, 
Lukas

**Comment by batermj** [comment]
Hi Lukas,
Yes, the code is under testing and will be available at this October.

Regards&Thanks,
Bater

2015-09-25 22:25 GMT+08:00 pendl notifications@github.com:

**Comment by pendl** [comment]
Hi Bater,
do you know exactly a date when the code will be available?
Kind Regards,
Lukas

**Comment by batermj** [comment]
Hi Lukas,
Yes, the code will be release at the end of next week.

Regards&Thanks,
Bater

2015-10-24 16:37 GMT+08:00 pendl notifications@github.com:
